---
permalink: linux-administration/concept_guidelines_forconnectingsnapshot_copies.html 
sidebar: sidebar 
keywords: snap, snapdrive, connect, snapshot, copy, guidelines 
summary: 連線至Snapshot複本時、請遵循準則。 
---
= 連接Snapshot複本的準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
連線至Snapshot複本時、請遵循準則。

* 「Snapsnap Connect」命令僅適用於以適用於UNIX的Snapshot 4.2建立的Snapshot複本。SnapDrive SnapDrive
* 在非原始主機上SnapDrive 、適用於UNIX的VMware®4.1支援使用Linux LVM1或LVM2執行Snapshot連線作業。但是、如果LUN是Linux LVM1 Volume Manager的一部分、則它不支援來源主機上的Snapshot連線作業。
* 在來源主機SnapDrive 上、適用於UNIX的支援連接及還原由舊版SnapDrive 的UNIX版所建立的Snapshot複本。
+

NOTE: 在Linux原始主機上、Snapshot連線作業僅適用於Linux LVM2、以及SnapDrive 由VMware為UNIX建立的Snapshot複本。

* 在Linux主機上、SnapDrive 如果您連線的Snapshot複本包含LUN、或是含有檔案系統的LUN、而該LUN是在不啟動Linux LVM1的情況下建立的、則支援「flexfsnap connect」命令。UNIX版不支援使用Linux LVM1建立的Linux實體使用「支援「支援鏈接」命令。SnapDrive SnapDrive
+
「支援鏈接」命令無法重新命名Linux主機上的磁碟群組。SnapDrive例如、下列命令不受支援：「SnapDrive /sfnap connect -dg dg 1 dg1copy -snapname taghap烤 麵包機：/vol/vol1：dg1snapshot」

* 如需NFS目錄樹的讀取和寫入存取權限、「SnapDrive Sfusnap Connect」命令會使用Data ONTAP FlexVol 「Sfor the volume」功能、因此需要Data ONTAP 使用更新版本的版本資訊。使用NetApp功能7.1的組態Data ONTAP 可連接NFS檔案或目錄樹狀結構、但提供唯讀存取。
* 如果您在Snapshot連線作業期間將「啟用-分割-複製」組態變數值設定為「On」或「Sync」、在Snapshot中斷作業期間設定為「Off」、SnapDrive 則UNIX版的Eshot不會刪除Snapshot複本中的原始Volume或LUN。
* 您必須將Data ONTAP 「vfz7.2.2」組態選項「vfiler.vol_clone _ZAPI_allow」的值設定為「on」、才能連線到vFiler單元中某個Volume或LUN的Snapshot複本。
* 具有不同主機組態的主機不支援Snapshot連線作業。
* 用來連線至實體儲存系統或vFiler單元的根Volume的「SnapDrive 鏈接」命令會失敗、因為Data ONTAP 無法複製根Volume。

