---
permalink: linux-administration/reference_error_message_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, error, message, value, common 
summary: 使用SnapDrive for UNIX時、您可能會看到一些較常見的錯誤訊息、並知道如何解決這些錯誤訊息、這對您來說很有幫助。 
---
= 錯誤訊息值
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapDrive for UNIX時、您可能會看到一些較常見的錯誤訊息、並知道如何解決這些錯誤訊息、這對您來說很有幫助。

下表提供使用SnapDrive for UNIX時最常見錯誤的詳細資訊：

[cols="15,20,15,25,40"]
|===
| 錯誤代碼 | 退貨代碼 | 類型 | 訊息 | 解決方案 


 a| 
「0000-001」
 a| 
不適用
 a| 
管理
 a| 
「Datapath已針對儲存系統設定。請使用SnapDrive 下列指令刪除此檔案：flexconfig DELETE -mgmtpath命令、然後重試。
 a| 
刪除儲存系統之前、請使用「SnapDrive show config DELETE -mgmtpath」命令刪除儲存系統設定的管理路徑。



 a| 
《0001-242》
 a| 
不適用
 a| 
管理
 a| 
「無法使用https連線至儲存系統：10.72.197.213。確保10.72.197.213是有效的儲存系統名稱/位址、 如果您所設定的儲存系統執行Data ONTAP 於7-Mode下的支援區、請將主機新增至信任的主機（選項為可信任的.hosts）、並在儲存系統10.72.197.213上啟用SSL、或修改SnapDrive。SnapDrive如果您設定的儲存系統執行於叢集Data ONTAP 式的功能、請確定Vserver名稱已對應至Vserver管理LIF的IP位址
 a| 
檢查下列情況：

* 請確定您所連接的儲存系統是有效的儲存系統。
* 如果您要設定的儲存系統正在Data ONTAP 7-Mode中執行、請在信任的主機上新增相同項目、並在儲存系統上啟用SSL、或修改「snapdrive.conf」檔案以使用HTTP進行通訊、然後重新啟動SnapDrive funesdaem.
* 如果您要設定的儲存系統正在叢集Data ONTAP 式的作業系統上執行、請確定Vserver名稱已對應至Vserver管理邏輯介面（LIF）的IP位址。




 a| 
《0003-004》
 a| 
不適用
 a| 
管理
 a| 
「無法從來賓作業系統取消儲存系統<storage system-name>上的LUN <lun-name>。原因：沒有從CoreOS填入對應裝置資訊
 a| 
當您SnapDrive 在客體作業系統中執行「不中斷連線」作業時、就會發生這種情況。

檢查ESX伺服器中是否有任何RDM LUN對應、或ESX伺服器中是否有過時的RDM項目。

在ESX伺服器和來賓作業系統中手動刪除RDM對應。



 a| 
《0001-019》
 a| 
3.
 a| 
命令
 a| 
「無效的命令列-重複的檔案支援：<DG1/vol2和DG1/vol2>'
 a| 
當執行的命令在同一個主機Volume上有多個主機實體時、就會發生這種情況。

例如、命令會明確指定同一個主機Volume上的主機Volume和檔案系統。

完成下列步驟：

. 移除主機實體的所有重複執行個體。
. 再次執行命令。




 a| 
《000-023》
 a| 
11.
 a| 
管理
 a| 
「無法探索磁碟群組DG1中的所有LUN。裝置沒有回應： DG1請檢查儲存系統上的LUN狀態、並視需要將LUN上線、或將主機新增至信任的主機（選項：可信任的.hosts）、並在儲存系統上啟用SSL、或是在變更SnapDrive．conf以使用（http / https）進行儲存系統通訊並重新啟動SnapDrive esfdaemon
 a| 
當設備上的SCSI查詢失敗時、就會發生此情況。由於多種原因、裝置上的SCSI查詢可能會失敗。

執行下列步驟：

. 將device-retries組態變數設定為較高的值。
+
例如、將其設為10（預設值為3）、然後再次執行命令。

. 使用SnapDrive 帶有「-all」選項的「zhi storage show」命令、即可取得有關裝置的資訊。
. 檢查儲存系統上的FC或iSCSI服務是否已啟動並正在執行。
+
如果沒有、請聯絡儲存系統管理員、讓儲存系統上線。

. 檢查主機上的FC或iSCSI服務是否正常運作。


如果上述解決方案無法解決問題、請聯絡技術支援部門。



 a| 
《0001-3995》
 a| 
不適用
 a| 
管理
 a| 
「這台主機上沒有HBA！
 a| 
如果您有大量LUN連線至主機系統、就會發生這種情況。

檢查在'snapdrive.conf文件中是否將變量'_ENable-fCP高速緩存_'設置爲ON。



 a| 
《0001-389》
 a| 
不適用
 a| 
管理
 a| 
"HBA assistant linufcp"無法取得HBA類型
 a| 
如果您有大量LUN連線至主機系統、就會發生這種情況。

檢查在'snapdrive.conf文件中是否將變量'_ENable-fCP高速緩存_'設置爲ON。



 a| 
《0001-389》
 a| 
不適用
 a| 
管理
 a| 
"HBA assistant vmwarefcp"無法取得HBA類型
 a| 
必須檢查下列條件：

* 在建立儲存設備之前、請務必使用下列命令來設定虛擬介面：


hes* SnapDrive 《*》組態集-viadmin <user><virtual_interface_ip or name>_*》

* 檢查儲存系統是否存在虛擬介面、但仍會出現相同的錯誤訊息、然後重新啟動SnapDrive 適用於UNIX的版次、以使儲存建立作業成功。
* 檢查您是否符合中所述的Virtual Storage Console組態需求 link:https://www.netapp.com/pdf.html?item=/media/7350-ds-3057.pdf["適用於VMware vSphere的NetApp虛擬儲存主控台"]




 a| 
《0001-682》
 a| 
不適用
 a| 
管理
 a| 
「Host Preparation for new LUN失敗：不支援此功能檢查控制器。
 a| 
再次執行命令SnapDrive 以使執行過程順利完成。



 a| 
《0001-859》
 a| 
不適用
 a| 
管理
 a| 
「主機的介面都沒有NFS權限可存取儲存系統上的目錄<儲存系統名稱>。
 a| 
在「snapdrive.conf」檔案中、確認「_Check匯出權限-nfs_clone_」組態變數設為「Off」。



 a| 
《0002-253》
 a| 
 a| 
管理
 a| 
無法建立Flex Clone複本
 a| 
這是儲存系統端的錯誤。請收集sd-trace.log和儲存系統記錄以進行疑難排解。



 a| 
「0002-2664」
 a| 
 a| 
管理
 a| 
「FlexClone不支援檔案管理器<Filer name>'
 a| 
FlexClone不支援目前Data ONTAP 版本的儲存系統。將儲存系統Data ONTAP 的更新版本升級至7.0或更新版本、然後重試命令。



 a| 
《0002-265》
 a| 
 a| 
管理
 a| 
「無法在檔案管理器上檢查flex_clone授權<filername>'
 a| 
這是儲存系統端的錯誤。收集sd-trace.log和儲存系統記錄以進行疑難排解。



 a| 
「0002-266」
 a| 
不適用
 a| 
管理
 a| 
「FlexClone未獲得檔案管理器<filername>'的授權
 a| 
FlexClone未在儲存系統上獲得授權。在儲存系統上新增FlexClone授權後、請重試此命令。



 a| 
「0002-267」
 a| 
不適用
 a| 
管理
 a| 
「FlexClone不支援root volume <volume名稱>
 a| 
無法為根磁碟區建立FlexClones。



 a| 
「0002-270」
 a| 
不適用
 a| 
管理
 a| 
「Aggregate上的可用空間小於磁碟群組/ FlexClone中繼資料所需的<Size> MB（MB）。
 a| 
. 若要使用FlexClones連線至原始LUN、則需要在Aggregate上提供2 MB可用空間。
. 請依照步驟1和步驟2在Aggregate上釋放一些空間、然後重試命令。




 a| 
「0002-3332」
 a| 
不適用
 a| 
管理
 a| 
「現在的快照。使用者lnx197/142\john的qtree storage array1：/vol/vol1/qtre1存取遭拒。
 a| 
請聯絡Operations Manager管理員、將所需的功能授予使用者。



 a| 
「0002-3664」
 a| 
不適用
 a| 
管理
 a| 
「無法聯絡DFM：lnx197/146、請變更使用者名稱和/或密碼。
 a| 
驗證並修正SD-admin使用者的使用者名稱和密碼。



 a| 
「0002-2668」
 a| 
不適用
 a| 
管理
 a| 
「<Volume名稱>不是彈性磁碟區」
 a| 
無法為傳統磁碟區建立FlexClones。



 a| 
「0003-003」
 a| 
 a| 
管理
 a| 
. 「無法將儲存系統上的LUN <LUN_name>匯出至來賓作業系統。
+
 or

 a| 
* 檢查ESX伺服器中的ESX伺服器（或）過時RDM項目中是否有任何RDM LUN對應。
* 在ESX伺服器和來賓作業系統中手動刪除RDM對應。




 a| 
「0003-012」
 a| 
 a| 
管理
 a| 
「虛擬介面伺服器win2k3-225-238無法連線。
 a| 
未針對主機/客體作業系統設定NIS。

您必須在位於「/etc/hosts」的檔案中提供名稱和IP對應

例如：「# cat /etc/hosts10.72.225.238 win2k3-225-238.eng.org.com win2k3-225-238」



 a| 
《0001-552》
 a| 
不適用
 a| 
命令
 a| 
「不是有效的Volume複製或LUN複製」
 a| 
無法為傳統磁碟區建立Clone分割。



 a| 
《0001-553》
 a| 
不適用
 a| 
命令
 a| 
「無法分割「FS-Name」、因為<Filer- Name>的儲存空間不足。
 a| 
Clone分割會繼續進行分割程序、但由於儲存系統中沒有足夠的儲存空間、因此實體分割會突然停止。



 a| 
「0003-002」
 a| 
 a| 
命令
 a| 
「無法再將LUN匯出至來賓作業系統。
 a| 
由於ESX伺服器支援控制器的裝置數量已達到上限、因此您必須為客體作業系統新增更多控制器。

*附註：* ESX伺服器將每個客體作業系統的控制器上限限制為4。



 a| 
"9000-023"
 a| 
1.
 a| 
命令
 a| 
「沒有關鍵字-LUN的引數」
 a| 
當關鍵字為「-LUN」的命令沒有「_LUN_name_」引數時、就會發生此錯誤。

處理方式：執行下列其中一項；

. 使用`-LUN'關鍵字指定命令的"_LUN_name_"引數。
. 請查看SnapDrive 《支援UNIX的支援消息




 a| 
《0001-028》
 a| 
1.
 a| 
命令
 a| 
「File system（檔案系統）」是SnapDrive 指不是由支援部門管理的類型（HFS）。請重新提交您的要求、並退出檔案系統<mnt/qa/DG4/vol1>'
 a| 
當不支援的檔案系統類型是命令的一部分時、就會發生此錯誤。

處理方式：排除或更新檔案系統類型、然後再次使用命令。

如需最新的軟體相容性資訊、請參閱互通性對照表。



 a| 
《9000-030》
 a| 
1.
 a| 
命令
 a| 
LUN不能與其他關鍵字結合使用
 a| 
當您將「-LUN」關鍵字與「-FS」或「-dg」關鍵字結合使用時、就會發生此錯誤。這是語法錯誤、表示命令使用無效。

處理方式：只能使用「-LUN」關鍵字再次執行命令。



 a| 
《000-034》
 a| 
1.
 a| 
命令
 a| 
「安裝失敗：掛載：不是有效的區塊裝置」
 a| 
只有當複製的LUN已連線至Snapshot複本中的相同檔案、然後您嘗試執行「SnapDrive 還原快照」命令時、才會發生此錯誤。

此命令失敗、因為當您刪除複製的LUN時、iSCSI精靈會重新對應已還原LUN的裝置項目。

處理方式：執行下列其中一項：

. 再次執行「SnapDrive 還原功能」命令。
. 在嘗試還原原始LUN的Snapshot複本之前、請先刪除連線的LUN（如果它安裝在與Snapshot複本相同的檔案中）。




 a| 
《0001-046 and 0001-047》
 a| 
1.
 a| 
命令
 a| 
「無效的快照名稱：</vol/vol1/NO_filer_prefied>或無效的快照名稱：NO_LON_FILNAME -檔案管理器磁碟區名稱遺失」
 a| 
這是一種語法錯誤、表示命令的使用無效、其中Snapshot作業是以無效的Snapshot名稱嘗試。

處理方式：完成下列步驟：

. 使用SnapDrive 「Isfsnap清單-檔案管理器<filer-volume名稱>」命令取得Snapshot複本清單。
. 使用long快照名稱引數執行命令。




 a| 
《9000-047》
 a| 
1.
 a| 
命令
 a| 
"More不只提供一個-snapname參數"
 a| 
UNIX版無法在命令列中接受多個Snapshot名稱來執行任何Snapshot作業。SnapDrive

處理方式：再次執行命令、只需一個Snapshot名稱。



 a| 
《9000年9月》
 a| 
1.
 a| 
命令
 a| 
不能組合使用-g和-vg
 a| 
當您合併「-dg」和「-vg」關鍵字時、就會發生此錯誤。這是語法錯誤、表示命令使用無效。

處理方式：使用「-dg」或「-vg」關鍵字執行命令。



 a| 
「9000-050」
 a| 
1.
 a| 
命令
 a| 
不能將「-lvol」和「-hostvol」合併
 a| 
當您結合了「-lvol'」和「-hostvol'關鍵字時、就會發生此錯誤。這是語法錯誤、表示命令使用無效。處理方式：完成下列步驟：

. 在命令列中、將「-lvol'」選項變更為「-hostvol'」選項、反之亦然。
. 執行命令。




 a| 
《9000年》（9000年-057年）
 a| 
1.
 a| 
命令
 a| 
"Marising required -snapname arg辯論"
 a| 
這是一種語法錯誤、表示命令的使用無效、在未提供Snap_name引數的情況下、會嘗試Snapshot作業。

處理方式：以適當的Snapshot名稱執行命令。



 a| 
《000-067》
 a| 
6.
 a| 
命令
 a| 
「Snapshot Hourly」（每小時快照）SnapDrive
 a| 
這些是Data ONTAP 由NetApp所建立的每小時自動Snapshot複本。



 a| 
《0001-092》
 a| 
6.
 a| 
命令
 a| 
「napshot <non-exist_24965>不存在於檔案保有者：」
 a| 
在儲存系統上找不到指定的Snapshot複本。處理方式：使用「SnapDrive 功能表」命令尋找儲存系統中的Snapshot複本。



 a| 
《0001-099》
 a| 
10.
 a| 
管理
 a| 
「無效的快照名稱：<Exocet:/vol2/dbvol:New SnapName>不符合檔案管理器磁碟區名稱<Exocet:/vol/vol1>'
 a| 
這是一種語法錯誤、表示命令的使用無效、其中Snapshot作業是以無效的Snapshot名稱嘗試。

處理方式：完成下列步驟：

. 使用「SnapDrive Sfsnap list - filer _<filer-volume名稱_」命令取得Snapshot複本清單。
. 以SnapDrive 正確格式的Snapshot名稱執行命令、該名稱由適用於UNIX的人選項進行驗證。這些合格格式包括：「_long快照名稱_」和「_short_snap名稱_」。




 a| 
《0001-1222》
 a| 
6.
 a| 
管理
 a| 
「無法在檔案管理器<Exocet>上取得快照清單：指定的磁碟區不存在。
 a| 
如果指定的儲存系統（檔案管理器）磁碟區不存在、就會發生此錯誤。

處理方式：完成下列步驟：

. 請聯絡儲存設備管理員以取得有效儲存系統磁碟區的清單。
. 以有效的儲存系統磁碟區名稱執行命令。




 a| 
《0001-124》
 a| 
111.
 a| 
管理
 a| 
「無法移除檔案管理器<Exocet>: LUN clone上的<snap_dete_multi_inuse _24374>。
 a| 
指定Snapshot複本的「快照刪除」作業失敗、因為存在LUN複本。

處理方式：完成下列步驟：

. 使用SnapDrive 含有「-all」選項的「支援功能」show命令、尋找Snapshot複本的LUN實體複本（Snapshot複本輸出的一部分）。
. 請聯絡儲存設備管理員、將LUN從實體複本分割開來。
. 再次執行命令。




 a| 
《0001-155》
 a| 
4.
 a| 
命令
 a| 
「napshot <dup_snapname239880>已存在於<Exocet:/vol/vol1>。請使用-f（force）旗標覆寫現有的snapshot
 a| 
如果命令中使用的Snapshot複本名稱已經存在、就會發生此錯誤。

處理方式：執行下列其中一項：

. 以不同的Snapshot名稱再次執行命令。
. 再次使用「-f'（force）」旗標執行命令、以覆寫現有的Snapshot複本。




 a| 
《0001-158》
 a| 
84.
 a| 
命令
 a| 
「Disgroup組態自<snapshotexocet:/vol/vo l1:Overwrite _noforce_25 078>被使用以來已變更。移除hostvolvol（開發/ DG3/vol4）請使用「-f」（強制）旗標來覆寫警告和完整還原
 a| 
磁碟群組可以包含多個LUN、當磁碟群組組組態變更時、您會遇到此錯誤。例如、建立Snapshot複本時、磁碟群組由X個LUN數組成、複製完成後、磁碟群組可以有X+Y個LUN數。

處理方式：使用「-f」（force）旗標再次使用命令。



 a| 
《0001-185》
 a| 
不適用
 a| 
命令
 a| 
「torage show f失敗：檔案管理器上沒有可顯示或啟用SSL的NetApp裝置、或是在變更SnapDrive．conf以使用http進行檔案管理器通訊之後重試。
 a| 
發生此問題的原因如下：

如果主機上的iSCSI精靈或FC服務已停止或故障、即使SnapDrive 主機上已設定LUN、「show -all」命令仍會失敗。

處理方式：解決發生故障的iSCSI或FC服務。

設定LUN的儲存系統已關閉或正在重新開機。

處理方式：等到LUN正常運作。

設置的'_usehttps- to -filer_'組態變數值可能不是支援的組態。

處理方式：完成下列步驟：

. 使用「lanlun LUN show all」命令檢查是否有任何LUN對應至主機。
. 如果有任何LUN對應至主機、請遵循錯誤訊息中所述的指示。


將'_usehttps- to -filer_'組態變數的值變更（如果值為「Off」、則變更為「On」；如果值為「On」、則變更為「Off」）。



 a| 
《0001-226》
 a| 
3.
 a| 
命令
 a| 
「「建立快照」需要所有檔案支援程式都可存取。請確認下列無法存取的檔案：檔案系統：</mnt/qa/DG1/vol3>'
 a| 
當指定的主機實體不存在時、就會發生此錯誤。

處理方式：SnapDrive 再次使用「支援全部」選項的「支援儲存show」命令、尋找主機上的主機實體。



 a| 
《0001-242》
 a| 
18
 a| 
管理
 a| 
「無法連線至檔案管理器：<filername>'
 a| 
適用於UNIX、嘗試透過安全HTTP傳輸協定連線至儲存系統。SnapDrive當主機無法連線至儲存系統時、可能會發生此錯誤。

處理方式：完成下列步驟：

. 網路問題：
+
.. 使用nslookups命令檢查通過主機工作的儲存系統的DNS名稱解析。
.. 如果儲存系統不存在、請將其新增至DNS伺服器。
+
您也可以使用IP位址、而非主機名稱來連線至儲存系統。



. 儲存系統組態：
+
.. 若要讓UNIX運作、您必須擁有安全HTTP存取的授權金鑰。SnapDrive
.. 設定授權金鑰之後、請檢查您是否可以透過網頁瀏覽器存取儲存系統。


. 執行步驟1或步驟2或兩者後執行命令。




 a| 
《0001-243》
 a| 
10.
 a| 
命令
 a| 
「無效的dg名稱：<SDU_dg1>'
 a| 
當主機中沒有磁碟群組、而命令隨後又失敗時、就會發生此錯誤。例如、主機中不存在「_SDU_DG1_」。

處理方式：完成下列步驟：

. 使用「SnapDrive flexstorage show -all」命令取得所有磁碟群組名稱。
. 以正確的磁碟群組名稱再次執行命令。




 a| 
《0001-246》
 a| 
10.
 a| 
命令
 a| 
「無效的主機磁碟區名稱：」、有效格式為<vgname/hostvolname>、亦即<mygroup / vol2>'
 a| 
處理方式：再次執行命令、並針對主機磁碟區名稱使用下列適當格式：「vgname/hostvolname」



 a| 
《0001-360》
 a| 
34
 a| 
管理
 a| 
「無法在檔案管理器<Exocet>上建立LUN </vol/badvol1/nanehp13_ unnewDg_fve_SdLun>：沒有這類磁碟區」
 a| 
當指定路徑包含不存在的儲存系統磁碟區時、就會發生此錯誤。

處理方式：請聯絡您的儲存系統管理員、取得可供使用的儲存系統磁碟區清單。



 a| 
《0001-372》
 a| 
58
 a| 
命令
 a| 
bad LUN name:+'、</vol/vol1/SCE_lun2a>- format not sivaled'（錯誤LUN名稱：：+'、</vol/vol1/SCE_lun2a>-無法識別格式）
 a| 
如果命令中指定的LUN名稱不符合SnapDrive 支援UNIX的預先定義格式、就會發生此錯誤。UNIX版要求以下列預先定義的格式指定LUN名稱：「<filer-name:/vol/<volname>/<lun-name>」SnapDrive

處理方式：完成下列步驟：

. 使用「SnapDrive 支援功能」命令來瞭解SnapDrive 支援UNIX的LUN名稱的預先定義格式。
. 再次執行命令。




 a| 
《0001-373》
 a| 
6.
 a| 
命令
 a| 
「找不到下列1個LUN：Exocet:</vol/vol1/NotARealLun>'
 a| 
如果在儲存系統上找不到指定的LUN、就會發生此錯誤。

處理方式：執行下列其中一項：

. 若要查看連接到主機的LUN、請使用「SnapDrive flexstorage show -dev'命令或「SnapDrive flexstorage show -all'命令」。
. 若要查看儲存系統上的完整LUN清單、請聯絡儲存設備管理員、從儲存系統取得LUN show命令的輸出。




 a| 
《0001-3777》
 a| 
43.
 a| 
命令
 a| 
「磁碟群組名稱<name>已在使用中、或與其他實體發生衝突。
 a| 
當磁碟群組名稱已在使用中或與其他實體發生衝突時、就會發生此錯誤。處理方式：執行下列其中一項：

. 使用"-autorename"選項執行命令
. 使用SnapDrive 帶有"-all"選項的"flexstorage show"命令查找主機所使用的名稱。執行命令、指定主機未使用的其他名稱。




 a| 
《0001-380》
 a| 
43.
 a| 
命令
 a| 
「Host volume name <DG3/vol1> is already in use or piscoles.」（主機磁碟區名稱<DG3/vol1>已在使用中、或與其他實體發生衝突。
 a| 
當主機磁碟區名稱已在使用中或與其他實體發生衝突時、就會發生此錯誤

處理方式：執行下列其中一項：

. 使用"-autorename"選項執行命令。
. 使用SnapDrive 帶有"-all"選項的"flexstorage show"命令查找主機所使用的名稱。執行命令、指定主機未使用的其他名稱。




 a| 
《0001-417》
 a| 
51.
 a| 
命令
 a| 
「下列名稱已經在使用中：<myDG1>。請指定其他名稱
 a| 
處理方式：執行下列其中一項：

. 使用「-autorename"選項再次執行命令。
. 使用「SnapDrive 支援儲存的show - all」命令來尋找主機上的名稱。再次執行命令、明確指定主機未使用的其他名稱。




 a| 
《0001-430》
 a| 
51.
 a| 
命令
 a| 
「您無法同時指定-dg/vg和- lvol/hostvoldg/vol.」
 a| 
這是一種語法錯誤、表示命令的使用無效。命令列可以接受「-dg/vg」關鍵字或「-lvol/hostvol'」關鍵字、但不能同時接受這兩個關鍵字。

處理方式：只使用「-dg/vg」或「-lvol/hostvol'」關鍵字執行命令。



 a| 
《0001-4334》
 a| 
6.
 a| 
命令
 a| 
「napshot Exocets/vol/vol1：no_E IST不存在於儲存磁碟區Exocets/vol/vol1」
 a| 
如果在儲存系統上找不到指定的Snapshot複本、就會發生此錯誤。

處理方式：使用「SnapDrive 功能表」命令尋找儲存系統中的Snapshot複本。



 a| 
《0001-435》
 a| 
3.
 a| 
命令
 a| 
「您必須在命令列上指定所有主機磁碟區和/或所有檔案系統、或是提供-autodExpand選項。命令列上缺少下列名稱、但快照<snap2_5vg_singlLUN _remoit>中卻有這些名稱：主機磁碟區：<DG3/vol2>檔案系統：</mnt/qa/DG3/vol2>'
 a| 
指定的磁碟群組具有多個主機磁碟區或檔案系統、但命令中並未提及完整的設定集。

處理方式：執行下列其中一項：

. 使用「- autodexpand」選項重新發出命令。
. 使用「SnapDrive flexsnap show」命令可找到完整的主機磁碟區和檔案系統清單。執行指定所有主機磁碟區或檔案系統的命令。




 a| 
《0001-440》
 a| 
6.
 a| 
命令
 a| 
「napshot snap2_5VG_SINGLELUN_遠端不包含磁碟群組'gBAD'」
 a| 
當指定的磁碟群組不是指定Snapshot複本的一部分時、就會發生此錯誤。

處理方式：若要尋找指定磁碟群組是否有任何Snapshot複本、請執行下列其中一項：

. 使用「SnapDrive 功能表」命令、在儲存系統中尋找Snapshot複本。
. 使用「SnapDrive flexfsnap show」命令尋找Snapshot複本中的磁碟群組、主機磁碟區、檔案系統或LUN。
. 如果磁碟群組存在Snapshot複本、請以Snapshot名稱執行命令。




 a| 
《0001-4442》
 a| 
1.
 a| 
命令
 a| 
「多個目的地-<dis>和<dis1>指定給單一SnapConnect來源<SR>。請使用個別命令重試
 a| 
處理方式：執行個別的「SnapDrive Isfsnap Connect」命令、使新的目的地磁碟群組名稱（屬於snap Connect命令的一部分）不同於同一個「SnapDrive flexap connect」命令中其他磁碟群組單元的名稱。



 a| 
《0001-465》
 a| 
1.
 a| 
命令
 a| 
「下列檔案不存在且無法刪除：磁碟群組：<naneHP13_DG1>」
 a| 
主機上不存在指定的磁碟群組、因此指定磁碟群組的刪除作業失敗。

處理方式：使用SnapDrive 「All」（全部）選項的「SHALL SHALL SHALL」命令、查看主機上的實體清單。



 a| 
《0001-476》
 a| 
不適用
 a| 
管理
 a| 
「無法探索與<long LUN name>相關的裝置。如果使用多重路徑、可能會發生多重路徑組態錯誤。請驗證組態、然後重試
 a| 
這種失敗的原因可能很多。

* 無效的主機組態：
+
iSCSI、FC或多重路徑解決方案未正確設定。

* 無效的網路或交換器組態：
+
IP網路未設定適當的iSCSI流量轉送規則或篩選器、或FC交換器未設定建議的分區組態。



上述問題很難以演算法或循序方式進行診斷。

處理方式：NetApp建議您SnapDrive 在使用for UNIX之前、先依照《主機公用程式設定指南》（適用於特定作業系統）中建議的步驟、手動探索LUN。

發現LUN之後、請使用SnapDrive 適用於UNIX的指令。



 a| 
《0001-486》
 a| 
12.
 a| 
管理
 a| 
「LUN正在使用中、無法刪除。請注意、移除Volume Manager控制下的LUN時、若不先從Volume Manager控制項中適當移除、將會產生危險。
 a| 
UNIX版無法刪除屬於Volume群組的LUN。SnapDrive

處理方式：完成下列步驟：

. 使用命令「SnapDrive flexstorage delete -dg <dgname>'」刪除磁碟群組。
. 刪除LUN。




 a| 
《0001-494》
 a| 
12.
 a| 
命令
 a| 
「SnapDrive 無法刪除<myDG1>、因為其中仍有1個主機磁碟區存在。使用-full旗標刪除所有與<myDG1>'相關的檔案系統和主機磁碟區
 a| 
UNIX版無法刪除磁碟群組、除非明確要求刪除磁碟群組中的所有主機磁碟區。SnapDrive

處理方式：執行下列其中一項：

. 在命令中指定「-full」旗標。
. 完成下列步驟：
+
.. 使用「SnapDrive flexstorage show -all」命令取得磁碟群組中的主機磁碟區清單。
.. 在UNIX適用的指令中、明確提及每一項SnapDrive 。






 a| 
《0001-541》
 a| 
65
 a| 
命令
 a| 
「存取權限不足、無法在檔案管理器上建立LUN、<Exocet>。
 a| 
UNIX版使用root儲存系統（檔案管理器）磁碟區上的「shdhostname.prbac」或「shdsgeneric.prbacfile」來執行其虛擬存取控制機制。SnapDrive

處理方式：執行下列其中一項：

. 修改「shd-hostname.prbac'」或「shd generic」。儲存系統中的prbac'檔案、以包含下列必要權限（可以是一或多個）：
+
.. 無
.. SnapCreate
.. 快照使用
.. 全部抓取
.. 儲存設備建立刪除
.. 儲存設備使用
.. 儲存全部
.. 所有存取權
+
*附註：*

+
[]
====
*** 如果您沒有「shd-hostname.prbac」檔案、請在儲存系統中修改「shdsgeneric.prbac」檔案。
*** 如果您同時擁有「shd-hostname.prbac"和「shdgeneric.prbac」檔案、則只能在儲存系統的「shdhostname.prbac"檔案中修改設定。


====


. 在「snapdrive.conf」檔案中、確定「all-access-if-rbacunspecified」組態變數設為「on」。




 a| 
《0001-559》
 a| 
不適用
 a| 
管理
 a| 
“在拍攝快照時選擇了I/O。請停止您的應用程式。請參閱SnapDrive 《資訊管理如需詳細資訊、請參閱指南
 a| 
如果您嘗試建立Snapshot複本、就會發生此錯誤、而平行輸入/輸出作業則發生在檔案規格上、而「shapcree-Cg - timeout」的值則設為「緊急」。

處理方式：將「shnapcree-CCG：timeout」的值設為「休閒」、以增加一致性群組逾時的值。



 a| 
《0001-570》
 a| 
6.
 a| 
命令
 a| 
「磁碟群組<DG1>不存在、因此無法調整大小」
 a| 
當主機中沒有磁碟群組、而命令隨後又失敗時、就會發生此錯誤。

處理方式：完成下列步驟：

. 使用「SnapDrive flexstorage show -all」命令取得所有磁碟群組名稱。
. 以正確的磁碟群組名稱執行命令。




 a| 
《0001-574》
 a| 
1.
 a| 
命令
 a| 
「<Vm助理> LVM不支援調整磁碟群組中的LUN大小」
 a| 
當用於執行此工作的Volume Manager不支援LUN大小調整時、就會發生此錯誤。

UNIX版的支援LUN大小調整取決於Volume Manager解決方案、如果LUN是磁碟群組的一部分。SnapDrive

處理方式：檢查您使用的Volume Manager是否支援LUN大小調整。



 a| 
《0001-616》
 a| 
6.
 a| 
命令
 a| 
在檔案管理器上找不到1個快照：Exocet：/vol/vol1：MySnapName>'
 a| 
UNIX版無法在命令列中接受多個Snapshot名稱來執行任何Snapshot作業。SnapDrive若要修正此錯誤、請以一個Snapshot名稱重新發出命令。

這是一種語法錯誤、表示命令的使用無效、其中Snapshot作業是以無效的Snapshot名稱嘗試。若要修正此錯誤、請完成下列步驟：

. 使用「SnapDrive Isfsnap清單-檔案管理器<filer-volume名稱>」命令取得Snapshot複本清單。
. 使用「* long快照名稱*」引數執行命令。




 a| 
「0001-640」
 a| 
1.
 a| 
命令
 a| 
「root檔案系統/不是SnapDrive 由功能性的系統管理」
 a| 
當主機上的root檔案系統不受SnapDrive UNIX版的支援時、就會發生此錯誤。這是對SnapDrive UNIX提出的無效要求。



 a| 
《0001-684》
 a| 
45
 a| 
管理
 a| 
「安裝表中已存在安裝點<fs_spec>。
 a| 
處理方式：執行下列其中一項：

. 使用不同的掛載點執行SnapDrive UNIX版的指令。
. 檢查掛載點是否未使用、然後手動（使用任何編輯器）從下列檔案刪除該項目：


Linux：/etc/Fstab



 a| 
《0001-796和0001-767》
 a| 
3.
 a| 
命令
 a| 
《0001-796和0001-767》
 a| 
UNIX版的同一個命令中不支援多個LUN、只能使用「-nolvm」選項。SnapDrive

處理方式：執行下列其中一項：

. 再次使用命令只指定一個具有「-nolvm」選項的LUN。
. 使用命令時不要使用「- nolvm」選項。這將使用主機中的受支援Volume Manager（如果有）。




 a| 
《2715》
 a| 
不適用
 a| 
不適用
 a| 
「Volume Restore Zphyr不可用於檔案管理器<檔案名稱>請繼續進行LUN還原」
 a| 
舊Data ONTAP 版的版本無法使用Volume Restore ZAPI。使用SFSR重新發出命令。



 a| 
《2278》
 a| 
不適用
 a| 
不適用
 a| 
「快照名稱>之後建立的快照沒有磁碟區複製...」 失敗
 a| 
分割或刪除複本



 a| 
《2280》
 a| 
不適用
 a| 
不適用
 a| 
「LUN已對應且不在作用中或快照<filespec-name>故障」
 a| 
取消對應/儲存設備會中斷主機實體的連線



 a| 
《2282》
 a| 
不適用
 a| 
不適用
 a| 
「SnapMirror關係不存在... 失敗
 a| 
. 刪除關聯、或
. 如果SnapDrive 已設定使用Operations Manager的for UNIX RBAC、請要求Operations Manager管理員授予使用者「.Dirfaps.DisruptBaseline'功能。




 a| 
《2286》
 a| 
不適用
 a| 
不適用
 a| 
「LUN不屬於<fsname>、在快照的磁碟區中是應用程式一致的... 失敗。Snapshot LUN並非由<fsname>擁有、這可能是應用程式不一致的
 a| 
驗證檢查結果中提及的LUN是否未被使用。之後才使用「-force」選項。



 a| 
《2289》
 a| 
不適用
 a| 
不適用
 a| 
「Snapshot <snapname>...之後沒有建立新的LUN ...」 失敗
 a| 
驗證檢查結果中提及的LUN是否未被使用。之後才使用「-force」選項。



 a| 
《2990》
 a| 
不適用
 a| 
不適用
 a| 
“無法執行不一致且更新的LUN檢查。Snapshot版本早於SDU 4.0
 a| 
當與「-vbsr」搭配使用時、使用適用於UNIX Snapshot的現象就會發生。SnapDrive手動檢查所建立的任何較新LUN將不再使用、然後繼續執行「-force」選項。



 a| 
《2292》
 a| 
不適用
 a| 
不適用
 a| 
「沒有新的快照存在... 失敗。建立的快照將會遺失。
 a| 
檢查檢查結果中提及的快照是否將不再使用。如果是、請繼續執行「-force」選項。



 a| 
"2297"
 a| 
不適用
 a| 
不適用
 a| 
正常檔案和LUN都存在... 失敗
 a| 
請確定檢查結果中提及的檔案和LUN不再使用。如果是、請繼續執行「-force」選項。



 a| 
《2302》
 a| 
不適用
 a| 
不適用
 a| 
"NFS匯出清單沒有外部主機... 失敗
 a| 
請聯絡儲存管理員、從匯出清單中移除外部主機、或確保外部主機未透過NFS使用磁碟區。



 a| 
《9000-305》
 a| 
不適用
 a| 
命令
 a| 
「無法偵測到/mnt/my_FS實體的類型。如果您知道實體類型、請提供特定選項（-LUN、-dg、-FS或-lvolol）
 a| 
如果實體已存在於主機中、請加以驗證。如果您知道實體的類型、請提供檔案規格類型。



 a| 
《9000-303》
 a| 
不適用
 a| 
命令
 a| 
「這個主機上有多個具有相同名稱的實體、例如/mnt/my_FS。針對您指定的實體提供特定選項（-LUN、-dg、-FS或-lvolol）
 a| 
使用者有多個具有相同名稱的實體。在此情況下、使用者必須明確提供檔案規格類型。



 a| 
《9000—304》
 a| 
不適用
 a| 
命令
 a| 
此命令不支援將/mnt/my_FS偵測為檔案系統類型的關鍵字
 a| 
此命令不支援對自動偵測的file_spec進行作業。請使用各自的操作說明進行驗證。



 a| 
《9000-301.》
 a| 
不適用
 a| 
命令
 a| 
「自動移轉發生內部錯誤」
 a| 
自動偵測引擎錯誤。提供追蹤和精靈記錄以供進一步分析。



 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
「napdrive.DC工具無法壓縮RHEL 5Ux環境中的資料」
 a| 
壓縮公用程式預設不會安裝。您必須安裝壓縮公用程式「ncompress」、例如「ncompress -4.2.4-47.i386.rpm」。

若要安裝壓縮公用程式、請輸入下列命令：「rpm -ivh ncomf-4.2.4-47.i386.rpm」



 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
「檔案無效」
 a| 
當指定的主機實體不存在或無法存取時、就會發生此錯誤。



 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
「工作ID無效」
 a| 
如果指定的工作ID無效或已查詢工作結果、則會針對複製分割狀態、結果或停止作業顯示此訊息。您必須指定有效或可用的工作ID、然後重試此作業。



 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
《plit is already progress》（正在進行中）
 a| 
下列情況會顯示此訊息：

* 特定Volume複製或LUN複製的實體複製分割已在進行中。
* 複本分割已完成、但不會移除工作。




 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
「不是有效的Volume複製或LUN複製」
 a| 
指定的檔案空間或LUN路徑名稱不是有效的Volume Clone或LUN Clone複製。



 a| 
不適用
 a| 
不適用
 a| 
命令
 a| 
「沒有空間可分割磁碟區」
 a| 
錯誤訊息是因為所需的儲存空間無法分割磁碟區。在Aggregate中釋放足夠空間、以分割Volume Clone。



 a| 
不適用
 a| 
不適用
 a| 
不適用
 a| 
「filer-data：jeting_dbsw資訊無法使用、LUN可能離線」
 a| 
如果不正確地設定了「etc/stb'」檔案、就可能發生此錯誤。在這種情況下、雖然掛載路徑是NFS、SnapDrive 但被用作UNIX的LUN。

處理方式：在檔案管理器名稱和交會路徑之間新增「/」。



 a| 
「0003-013」
 a| 
不適用
 a| 
命令
 a| 
「虛擬介面伺服器發生連線錯誤。請檢查虛擬介面伺服器是否已啟動並正在執行
 a| 
當ESX伺服器中的授權到期且VSC服務未執行時、可能會發生此錯誤。

處理方式：安裝ESX Server授權並重新啟動VSC服務。



 a| 
「0002-137」
 a| 
不適用
 a| 
命令
 a| 
「無法從Snapshot 10.231.72.21取得fsttype和mntOps：/vol/ips_vol3：/vol/ips_vol3：nfssnap。
 a| 
處理方式：執行下列其中一項

. 將資料路徑介面的IP位址或特定IP位址新增為主機名稱至「/etc/hosts」檔案。
. 在DNS中建立資料路徑介面或主機名稱IP位址的項目。
. 設定Vserver的資料生命期、以支援Vserver管理（使用防火牆原則=管理）
+
「* net int modify -vserver vserver_nameLIF_name-firewall-policy_mgmt*」

. 將主機的管理IP位址新增至Vserver的匯出規則。




 a| 
《13003》
 a| 
不適用
 a| 
命令
 a| 
「權限不足：使用者無法讀取此資源。
 a| 
此問題可在SnapDrive UNIX 5.2.2版的介紹中找到。在UNIX 5.2.2版之前、在for UNIX中設定的vsadmin使用者必須扮演「vsadmin_volume」角色。SnapDrive SnapDrive從UNIX 5.2.2的版本中、vsadmin使用者需要提升存取角色、否則SnapMirror-Get-iter ZAPI會失敗。SnapDrive

處理方式：建立角色vsadmin而非vsadmin_volume、然後指派給vsadmin使用者。



 a| 
《0001-16》
 a| 
不適用
 a| 
命令
 a| 
「無法取得儲存系統上的鎖定檔案。
 a| 
快照建立失敗、因為磁碟區空間不足。或是儲存系統中存在「.SnapDrive檔案鎖定」。

處理方式：執行下列其中一項：

. 刪除儲存系統上的檔案「/vol/<volname>//.SnapDrive鎖定」、然後重試Snapcreate作業。若要刪除檔案、請登入儲存系統、進入進階權限模式、並在儲存系統提示字元下執行「rm /vol/<volname>//.SnapDrive _lock」命令。
. 在拍攝快照之前、請先確認磁碟區中有足夠的可用空間。




 a| 
「0003-003」
 a| 
不適用
 a| 
管理
 a| 
「無法將儲存系統上的LUN匯出至來賓作業系統。原因：流程11019：MapStorage故障：沒有設定介面的儲存系統
 a| 
由於ESX伺服器中未設定儲存控制器、因此發生此錯誤。

處理方式：在ESX伺服器中新增儲存控制器和認證。



 a| 
《0001-4993》
 a| 
不適用
 a| 
管理
 a| 
「建立掛載點時發生錯誤：mkdir發生非預期的錯誤：mkdir：無法建立目錄：權限遭拒檢查掛載點是否位於automount路徑下。
 a| 
當目的地檔案規格位於自動掛載路徑之下時、複製作業會失敗。

處理方式：確定目的地檔案處理/掛載點不在自動掛載路徑下。



 a| 
「0009：049」
 a| 
不適用
 a| 
管理
 a| 
「從儲存系統的快照還原失敗：無法從Vserver上的Volume Snapshot複本還原檔案。
 a| 
當磁碟區大小已滿或磁碟區已超過自動刪除臨界值時、就會發生此錯誤。

處理方式：增加磁碟區大小、並確保磁碟區的臨界值維持在自動刪除值以下。



 a| 
《0001-682》
 a| 
不適用
 a| 
管理
 a| 
「Host Preparation for new LUN失敗：不支援此功能。
 a| 
當新LUN ID建立失敗時、就會發生此錯誤。

處理方式：增加要使用建立的LUN數量

「SnapDrive *」指的是「準備LUN」、包括：-count count_value_*

命令。



 a| 
《0003-060》
 a| 
不適用
 a| 
管理
 a| 
「無法取得磁碟群組的相關資訊：Volume Manager linuxlvms傳回vgdisplay命令失敗。
 a| 
當RHEL 5及更新版本使用適用於UNIX 4.1.1及更新版本時、就會發生此錯誤SnapDrive 。

處理方式：升級SnapDrive 支援功能、然後重試、因為SnapDrive 支援功能不適用於RHEL5及更新版本的UNIX 4.1.1及更新版本。



 a| 
「0009：045」
 a| 
不適用
 a| 
管理
 a| 
「在儲存系統上建立快照失敗：由於複本以快照做為備份、因此不允許執行快照作業。稍後再試一次
 a| 
此錯誤發生於單一檔案快照還原（SFSR）作業、然後立即建立快照。

處理方式：稍後重試Snapshot建立作業。



 a| 
《0001-304》
 a| 
不適用
 a| 
管理
 a| 
「建立磁碟/磁碟區群組時發生錯誤：Volume Manager失敗、原因如下：metainit：沒有這樣的檔案或目錄。
 a| 
使用SnapDrive Sun Cluster環境執行Sesfstorage create dg、hostvol和FS Solaris時、會發生此錯誤。

處理方式：解除安裝Sun Cluster軟體、然後重試作業。



 a| 
《0001-1222》
 a| 
不適用
 a| 
管理
 a| 
「無法在檔案管理器上取得快照清單、指定的磁碟區<volname>不存在。
 a| 
當UNIX版的Runf2嘗試使用已匯出的Volume作用中檔案系統路徑（實際路徑）、而非假匯出的Volume路徑來建立Snapshot時、就會發生此錯誤SnapDrive 。

處理方式：將磁碟區與匯出的作用中檔案系統路徑搭配使用。



 a| 
《0001-476》
 a| 
不適用
 a| 
管理
 a| 
「無法找到裝置。如果使用多重路徑、可能會發生多重路徑組態錯誤。請驗證組態、然後重試
 a| 
發生此錯誤的原因有多種。

請檢查下列條件：在建立儲存設備之前、請先確認分區正確無誤。

檢查「snapdrive.conf」檔案中的傳輸傳輸傳輸傳輸傳輸協定和多重路徑類型、並確保設定適當的值。

如果多重路徑類型設為nativempio start multipathd、請檢查多重路徑精靈狀態、然後重新啟動快照精靈。



 a| 
不適用
 a| 
不適用
 a| 
不適用
 a| 
因為無法使用lv、所以重新開機後、FS無法掛載
 a| 
當重新開機後無法使用lv時、就會發生這種情況。因此不會掛載檔案系統。

處理方式：重新開機後、執行vgchange（可啟動lv）、然後掛載檔案系統。



 a| 
不適用
 a| 
不適用
 a| 
不適用
 a| 
「與SDU精靈的狀態呼叫失敗。
 a| 
發生此錯誤的原因有多種。此錯誤表示SnapDrive 、與特定作業相關的UNIX版功能在作業完成之前、突然失敗（子精靈結束）。

如果建立或刪除儲存設備失敗並顯示「Status呼叫SnapDrive for UNIX精靈失敗」、可能是因為無法呼叫ONTAP 以取得Volume資訊。Volume取得者ZAPI可能會失敗。稍後再重試SnapDrive 執行此功能。

由於不適當的「多路徑.conf」值、UNIX作業在建立分割區或其他作業系統命令時執行「kpartx -l」時可能會失敗。SnapDrive確保設定適當的值、且「多重路徑.conf」檔案中不存在重複的關鍵字。

執行SFSR時SnapDrive 、針對UNIX的Sfing會建立暫時性Snapshot、如果快照值達到上限、則該Snapshot可能會失敗。刪除舊快照、然後重試還原作業。



 a| 
不適用
 a| 
不適用
 a| 
不適用
 a| 
「使用中的地圖、無法清除」
 a| 
如果在儲存設備刪除或中斷連線作業期間、嘗試清除多重路徑裝置時、有任何過時的裝置會留下此錯誤。

處理方式：執行命令、檢查是否有任何過時的裝置

‘*多重路徑*’

'_l egrep -ifail_'並確保在'multiPath.conf'檔案中、'_flush_on_last _del_'設為'yes'。

|===
*相關資訊*

https://mysupport.netapp.com/NOW/products/interoperability["NetApp互通性"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["《Linux Unified Host Utilities 7.1安裝指南》"]
