---
permalink: linux-administration/task_enabling_multipathing.html 
sidebar: sidebar 
keywords: snap, snapdrive, multipathing, enable, hba 
summary: 若要在SnapDrive UNIX中使用多重路徑、您必須完成安裝和啟動HBA的步驟。如果您使用的是非NetApp多重路徑解決方案、則必須從HBA廠商的網站下載軟體與應用程式套件。 
---
= 啟用多重路徑
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在SnapDrive UNIX中使用多重路徑、您必須完成安裝和啟動HBA的步驟。如果您使用的是非NetApp多重路徑解決方案、則必須從HBA廠商的網站下載軟體與應用程式套件。

您的系統必須執行目前版本的FC和iSCSI系統元件。

http://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"]

.步驟
. 安裝適當的主機公用程式軟體之前、請先安裝支援的HBA。
+

NOTE: 適用於UNIX的支援多廠商HBA。SnapDrive

. 啟動HBA服務。
+
如果HBA服務未執行、當您執行SnapDrive 支援UNIX的指令時、會顯示下列錯誤訊息、例如「SnapDrive 不支援儲存的建立」和SnapDrive 「不支援的組態準備LUN」：

+
[listing]
----
0001-876 Admin error: HBA assistant not found
----
+
您必須驗證所需的路徑數目是否已啟動並正在執行。您可以使用Host Utilities軟體隨附的「sanlun」公用程式來驗證路徑。例如、在FC多重路徑組態中、您可以使用「暫停FCP show介面卡-v」命令。

+
在下列範例中、有兩個HBA連接埠（fcd0和fcd1）連接至運作中的主機（連接埠狀態）。您只能擁有一個HBA或iSCSI啟動器、而且必須提供多個路徑來設定多重路徑、才能通往目標LUN。

+
[listing]
----
# sanlun fcp show adapter -v
adapter name: fcd0
WWPN: 50060b000038c428
WWNN: 50060b000038c429
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 1 of 2
port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd0
adapter name: fcd1
WWPN: 50060b000038c42a
WWNN: 50060b000038c42b
driver name: fcd
model: A6826A
model description: Fibre Channel Mass Storage Adapter
(PCI/PCI-X)
serial number: Not Available
hardware version: 3
driver version: @(#) libfcd.a HP Fibre Channel
ISP 23xx & 24xx Driver B.11.23.04
/ux/core/isu/FCD/kern/src/common/wsio/fcd_init.c:Oct 18
2005,08:19:50
firmware version: 3.3.18
Number of ports: 2 of 2 port type: Fabric
port state: Operational
supported speed: 2 GBit/sec
negotiated speed: 2 GBit/sec
OS device name: /dev/fcd1
----
+
如果在主機上啟用多重路徑、則相同LUN的多個路徑會顯示出來。您可以使用「左LUN show all」命令來驗證路徑。在下列範例中、您可以找到多個路徑、指向同一個LUN（「fish：/vol/vol1/LUN」）：

+
[listing]
----
 [root@lnx221-75 ~]# sanlun lun show
filer:        lun-pathname device filename adapter protocol lun size lun state
f960-221-167: /vol/vol1/lun1 /dev/sdd host5 FCP 100m (104857600)      GOOD
f960-221-167: /vol/vol1/lun1 /dev/sdc host6 FCP 100m (104857600)      GOOD
----
. 如果SnapDrive UNIX或主機公用程式支援協力廠商的多重路徑解決方案、請從HBA廠商的網站下載HBA驅動程式軟體套件和應用程式套件。* QLogic *：如需QLogic HBA、請前往 http://support.qlogic.com/[]。從OEM機型中選取NetApp。找到Support Matrix中列出的驅動程式版本、然後下載。* Emulex：*適用於Emulex HBA、請前往 http://www.emulex.com/ts/index.html[]。從「Downloads（下載）」選取「NetApp」。找到Support Matrix中列出的驅動程式版本、然後下載。也可從相同位置下載Emulex應用程式套件。
+
如果您使用的是具有FC連線功能的QLogic介面卡、請從QLogic網站下載QLogic重新掃描指令碼、然後將其複製到「/root」路徑（例如、「/root/動態-LUN-resce.sh」）。QLogic重新掃描指令碼會要求使用者確認、SnapDrive 而在這個確認階段、適用於UNIX的功能可能會無限期停機。您可以將指令碼中的變數「_QL_disable_warning_」設定為「1」、以避免此確認。

+
舊版SnapDrive 的UNIX版使用廠商專屬的SCSI重新掃描指令碼、透過FC掃描LUN、然後將廠商專屬的指令碼複製到「/root/動態-LUN-resce.sh」。此功能在RHEL 5U3之前提供。

+
對於RHEL 5U4/SLES 10SP2及更新版本、重新掃描指令碼目前位於「/rusr/bin」目錄中。如果重新掃描指令碼在目錄中無法使用、則會與「sg3_utils」套件一起出現。

+

NOTE: 您必須確保Red Hat Enterprise Linux（RHEL）和Oracle Enterprise Linux（OEL）版本均可使用「sg3_utils」和「sg3_utils-libs」程式庫。不過、在「scSCi utils.rpm」套件中的「sg3_utils」程式庫可用於SUSE Linux Enterprise Server（SLES）版本。

. 在FC組態中、使用交換器分區組態來分區主機HBA連接埠和目標連接埠。
. 安裝並設定適當的FC交換器。
. 檢查SnapDrive UNIX堆疊需求的功能。
. 安裝或升級SnapDrive 適用於UNIX的功能。
. 驗SnapDrive 證UNIX版的安裝過程。
. 找到「snapdrive.conf」檔案路徑。
. 在「snapdrive.conf（檔案）”中設定下列組態變數：
+
** 多重路徑類型_
** 缺省傳輸
** fstype_'
** vmtype_'
+
對於每個主機、多重路徑類型、傳輸類型、檔案系統和Volume Manager類型彼此相依。下表說明所有可能的組合：

+
|===
| 主機平台 | 預設傳輸類型 | 多重路徑類型 | FSType | vmtype 


 a| 
Linux
 a| 
iSCSI
 a| 
nativempio
 a| 
ext4或ext3
 a| 
LVM



 a| 
iSCSI
 a| 
無
 a| 
ext4或ext3
 a| 
LVM



 a| 
FCP
 a| 
無
 a| 
ext4或ext3
 a| 
LVM



 a| 
FCP
 a| 
nativempio
 a| 
ext4或ext3
 a| 
LVM

|===
+
上表提供了所支援的「多重路徑類型」、「預設傳輸」、「_fstype_」及「_vmtype_」組態變數值。

+

NOTE: 如果傳輸傳輸傳輸傳輸協定為「iSCSI」、而且多重路徑類型設為「無」、您應該停止多重路徑精靈並執行SnapDrive UNIX指令的支援。



. 儲存「snapdrive.conf」檔案。
+
UNIX版的還原功能會在每次啟動時自動檢查此檔案。SnapDrive您必須重新啟動SnapDrive UNIX版的功能、變更才會生效。



*相關資訊*

xref:concept_snaprestore_and_snapconnect_operations_do_not_work_in_linux_after_multipathing_migration.adoc[在移轉多重路徑類型之後、在Linux中執行的不再是執行支援和SnapConnect作業SnapRestore]

http://mysupport.netapp.com["NetApp支援"]

https://mysupport.netapp.com/NOW/products/interoperability["NetApp互通性"]

https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["《Linux Unified Host Utilities 7.1安裝指南》"]
