---
permalink: linux-administration/task_displaying_asnapshot_copy.html 
sidebar: sidebar 
keywords: snap, snapdrive, snapshot, shot, list, command 
summary: 命令SnapDrive Isfsnap show或list會顯示建立Snapshot複本的儲存系統名稱、主機名稱、日期和時間等。 
---
= 顯示Snapshot複本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
命令「SnapDrive flexsnap show」或「list」會顯示建立Snapshot複本的儲存系統名稱、主機名稱、日期和時間等。

.步驟
. 輸入下列命令語法以顯示Snapshot複本：
+
hy* SnapDrive 快照顯示[-snapname] long快照名稱[snap名稱...] [-verbosed]*



此作業至少會顯示下列有關Snapshot複本的資訊：

* 建立Snapshot複本的儲存系統名稱
* 執行Snapshot複本的主機名稱
* 儲存系統上LUN的路徑
* 建立Snapshot複本的日期與時間
* Snapshot複本的名稱
* Snapshot複本中包含的磁碟群組名稱


*範例*：以下是「SnapDrive 不知道的show命令：

[listing]
----
# snapdrive snap show -snapname toaster:/vol/vol2:snapA snapX snapY

# snapdrive snap show -verbose toaster:/vol/vol2:snapA /vol/vol3:snapB snapC

# snapdrive snap show toaster:/vol/vol2:snapA

# snapdrive snap list -dg dg1 dg2
----
*範例*：此範例使用萬用字元來顯示特定磁碟區上可用Snapshot複本的相關資訊：

[listing]
----
# snapdrive snap show toaster:/vol/vol1:*
snap name host date
snapped
------------------------------------------------------------------
-------------
toaster:/vol/vol1:sss1 DBserver Mar 12
16:19 dg1
toaster:/vol/vol1:testdg DBserver Mar 12
15:35 dg1
toaster:/vol/vol1:t1 DBserver Mar 10
18:06 dg1
toaster:/vol/vol1:hp_1 HPserver Mar 8
19:01 vg01
toaster:/vol/vol1:r3 DBserver Mar 8
13:39 rdg1
toaster:/vol/vol1:r1 DBserver Mar 8
13:20 rdg1
toaster:/vol/vol1:snap2 DBserver Mar 8
11:51 rdg1toaster:/vol/vol1:snap_p1 DBserver
Mar 8 10:18 rdg1
----
*範例*：此範例顯示Linux主機上NFS掛載目錄樹狀結構的Snapshot複本、使用SnapDrive 含有「- verbose」選項的「支援快照清單」命令：

[listing]
----
# snapdrive snap list -fs /mnt/acctfs1 -v
snap name host date
snapped
------------------------------------------------------------------
----------
besser:/vol/vol1:acctfs-s1 childs Aug 8 18:58
/mnt/acctfs1
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: acctfs-s1 file system: type: nfs mountpoint:
/mnt/acctfs1
filer dir: besser:/vol/vol1
----
*範例*：此範例在SnapDrive Linux主機上執行flexfsnap show命令：

[listing]
----
# snapdrive snap show -snapname surf:/vol/vol1:swzldg5snapped
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
#
# ./linux/ix86/snapdrive snap show -v -snapname
surf:/vol/vol1:bagel5snapped >
snap name host date
snapped
------------------------------------------------------------------
-------------
surf:/vol/vol1:bagel5snapped pons Aug 18
20:06 dg5
host OS: Linux 2.4.21-9.ELsmp #1 SMP Thu Jan 8 17:08:56 EST 2004
snapshot name: bagel5snapped
Volume Manager: linuxlvm 1.0.3
disk group: dg5
host volume: vol1
host volume: vol2
host volume: vol3
lun path dev paths
-------------------------------------------------------
surf:/vol/vol1/glk19 /dev/sdu
----
*範例*：下列範例使用萬用字元：

[listing]
----
# snapdrive snap show toaster:/vol/volX:*
# snapdrive snap show -v toaster:/vol/volX:DB1*
filer1:/vol/volY:DB2*
# snapdrive snap show toaster:/vol/vol2:mysnap* /vol/vol2:yoursnap*
hersnap*
# snapdrive snap show toaster:/vol/volX:*
----
*範例*：在此範例中、萬用字元的使用無效、因為萬用字元位於名稱中間、而非置於結尾：

[listing]
----
# snap show toaster:/vol/vol1:my*snap
----