---
permalink: aix/concept_multiple_operations_manager_servers.html 
sidebar: sidebar 
keywords: snap, snapdrive, multiple, operations, manager, console, server 
summary: 適用於UNIX的支援多部Operations Manager主控台伺服器。SnapDrive當一組儲存系統由多個Operations Manager主控台伺服器管理時、就需要此功能。UNIX版的聯絡Operations Manager主控台伺服器的順序、與Operations Manager主控台伺服器在UNIX版的中設定的順序相同。SnapDrive SnapDrive您可以執行SnapDrive flexconfig list命令來取得組態順序。 
---
= 多部Operations Manager主控台伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
適用於UNIX的支援多部Operations Manager主控台伺服器。SnapDrive當一組儲存系統由多個Operations Manager主控台伺服器管理時、就需要此功能。UNIX版的聯絡Operations Manager主控台伺服器的順序、與Operations Manager主控台伺服器在UNIX版的中設定的順序相同。SnapDrive SnapDrive您可以執行「SnapDrive 效能分析清單」命令來取得組態順序。

下列範例顯示多個Operations Manager主控台伺服器的輸出：

[listing]
----
# snapdrive config list
username    appliance name     appliance type
---------------------------------------------
root        storage_array1     StorageSystem
root        storage_array2     StorageSystem
sd-admin    ops_mngr_server1   DFM
sd-admin    ops_mngr_server2   DFM
----
在前一個範例中、server_array1由ops_mngr_server1管理、而storage _array2則由ops_mngr_server2管理。在此範例中SnapDrive 、UNIX的支援功能會先聯絡ops_mngr_server1。如果ops_mngr_server1無法判斷存取權、SnapDrive 則適用於UNIX的支援功能會聯絡ops_mngr_server2。

UNIX版僅在下列情況下聯絡第二個Operations Manager主控台：SnapDrive

* 當第一個Operations Manager主控台無法判斷存取權時。這種情況可能是因為第一個Operations Manager主控台並未管理儲存系統。
* 當第一個Operations Manager主控台關閉時。

