---
permalink: aix/reference_exit_status_values.html 
sidebar: sidebar 
keywords: snap, snapdrive, exit, status, value 
summary: 每個結束狀態值都有錯誤名稱、以及與其相關的類型。檢視表格以瞭解退出狀態值、錯誤名稱、類型及說明。 
---
= 結束狀態值
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個結束狀態值都有錯誤名稱、以及與其相關的類型。檢視表格以瞭解退出狀態值、錯誤名稱、類型及說明。

下表包含有關結束狀態值的資訊。結束狀態值會依序編號。如果SnapDrive UNIX版的不實作錯誤、則表格中不會包含該結束狀態值。因此、數字可能會有一些落差。

|===
| 結束值 | 錯誤名稱 | 類型 | 說明 


 a| 
1.
 a| 
不支援
 a| 
命令錯誤
 a| 
此版本SnapDrive 的UNIX版不支援所叫用的功能。



 a| 
2.
 a| 
無記憶體
 a| 
致命的
 a| 
系統記憶體不足。UNIX版無法繼續、除非您釋出足夠的記憶體、讓它正常運作。SnapDrive檢查其他執行中的應用程式、確認它們不會耗用過多的記憶體。



 a| 
3.
 a| 
無效命令
 a| 
命令錯誤
 a| 
您發出的命令無效；這可能是您輸入命令的文字語法錯誤。



 a| 
4.
 a| 
已存在
 a| 
命令錯誤
 a| 
您要求建立已存在的項目。通常、此錯誤是指Snapshot複本名稱、而該名稱不得存在於您正在製作Snapshot複本的儲存系統磁碟區上。



 a| 
5.
 a| 
建立執行緒失敗
 a| 
管理錯誤
 a| 
UNIX版的無法建立處理程序執行緒。SnapDrive檢查系統上執行的其他程序、確定有足夠的執行緒資源可用。



 a| 
6.
 a| 
找不到
 a| 
命令錯誤
 a| 
您在SnapDrive 不存在的適用於UNIX的命令列上加入檔案、資料群組、主機磁碟區、檔案系統或其他引數。



 a| 
7.
 a| 
不是掛載的檔案系統
 a| 
命令錯誤
 a| 
您要存取的檔案系統不是有效的檔案系統、或是未掛載。



 a| 
9.
 a| 
Volume Manager錯誤
 a| 
命令錯誤
 a| 
存取Volume Manager時傳回錯誤。請參閱特定錯誤訊息、以取得錯誤的詳細資料及原因。



 a| 
10.
 a| 
無效名稱
 a| 
命令錯誤
 a| 
您在命令列上提供的名稱格式不正確。

例如、儲存系統磁碟區未指定為「filer/vol/vol_name」。當儲存系統或Volume Manager型名稱中有無效字元時、也會出現此訊息。



 a| 
11.
 a| 
找不到裝置
 a| 
管理錯誤
 a| 
適用於UNIX的無法存取您要製作Snapshot複本之磁碟群組中的LUN。SnapDrive

檢查主機和儲存系統上所有LUN的狀態。此外、請檢查儲存系統磁碟區是否在線上、以及儲存系統是否已啟動並連線至主機。



 a| 
12.
 a| 
忙碌中
 a| 
命令錯誤
 a| 
LUN裝置、檔案、目錄、磁碟群組、主機Volume、 或其他實體忙碌中。

這通常是一種非致命錯誤、會在您重試命令時消失。它有時會指出資源或程序已掛起、導致物件忙碌且無法SnapDrive 供UNIX使用。

也可能表示您在I/O流量過大而無法成功製作Snapshot複本的期間、嘗試製作Snapshot複本。



 a| 
13.
 a| 
無法初始化
 a| 
致命的
 a| 
UNIX版無法初始化所需的第三方資料。SnapDrive這可以指檔案系統、Volume Manager、主機叢集軟體、多重路徑軟體等。



 a| 
14
 a| 
使用中SnapDrive
 a| 
使用中SnapDrive
 a| 
另一個使用者或程序正在同一個主機或儲存系統上執行作業、同時要求SnapDrive UNIX執行作業。重試您的作業。

偶爾此訊息表示其他程序會掛起、您必須將其終止。


NOTE: 在某些情況下、Snapshot還原作業可能需要很長時間。請確定您認為已中斷的程序不只是等待Snapshot還原作業完成。



 a| 
15
 a| 
組態檔錯誤
 a| 
致命的
 a| 
SnapDrive .conf檔案的項目無效、不足或不一致。如需詳細資料、請參閱特定錯誤訊息。您必須先修正此檔案、SnapDrive 才能繼續使用UNIX版。



 a| 
17
 a| 
權限不正確
 a| 
命令錯誤
 a| 
您沒有執行此命令的權限。您必須以root登入才能執行SnapDrive UNIX的功能。



 a| 
18
 a| 
無檔案管理器
 a| 
管理錯誤
 a| 
UNIX版無法連絡此命令所需的儲存系統。SnapDrive檢查錯誤訊息中所示的儲存系統連線能力。



 a| 
19
 a| 
檔案管理器登入錯誤
 a| 
管理錯誤
 a| 
UNIX版無法使用您提供的登入資訊登入儲存系統。SnapDrive



 a| 
20
 a| 
不良授權
 a| 
管理錯誤
 a| 
UNIX服務SnapDrive 需求未經授權可在此儲存系統上執行。



 a| 
22
 a| 
無法凍結FS
 a| 
管理錯誤
 a| 
Snapshot建立作業失敗、因為SnapDrive UNIX版的無法凍結指定的檔案系統、以製作Snapshot複本。確認系統I/O流量足夠輕、足以凍結檔案系統、然後重試命令。



 a| 
27
 a| 
Snapshot複本不一致
 a| 
管理錯誤
 a| 
Snapshot還原作業失敗、因為您要求從Snapshot複本還原磁碟群組映像不一致。在下列情況下可能會發生不一致的映像：

* 您並未使用SnapDrive 適用於UNIX的功能來製作Snapshot複本。
* Snapshot建立作業在設定一致的位元之前中斷、因此無法清除（如發生災難性系統故障時）。
* Snapshot複本製完成後、發生某種類型的資料問題。




 a| 
28.28
 a| 
HBA故障
 a| 
管理錯誤
 a| 
UNIX版嘗試從HBA擷取資訊時發生錯誤。SnapDrive



 a| 
29
 a| 
不良中繼資料
 a| 
管理錯誤
 a| 
UNIX版的Snapshot複本中繼資料在建立Snapshot複本時發生錯誤。SnapDrive



 a| 
30
 a| 
無Snapshot複本中繼資料
 a| 
管理錯誤
 a| 
UNIX版的支援無法執行Snapshot還原作業、因為中繼資料不包含所有要求的磁碟群組。SnapDrive



 a| 
31
 a| 
密碼檔案錯誤
 a| 
管理錯誤
 a| 
密碼檔案的項目不正確。使用「SnapDrive flexconfig DELETE」命令刪除此儲存系統的登入項目。然後使用「SnapDrive flexconfig set _user_name_」命令重新輸入登入資訊。



 a| 
33
 a| 
無密碼檔案項目
 a| 
管理錯誤
 a| 
密碼檔案沒有此儲存系統的項目。針對SnapDrive 需要執行SnapDrive UNIX版的各個儲存系統、執行「支援組態集_使用者名稱_」命令。然後再試一次此作業。



 a| 
34
 a| 
不是NetAPPLUN
 a| 
管理錯誤
 a| 
UNIX版的某個指令遇到的LUN不在NetApp儲存系統上。SnapDrive



 a| 
35
 a| 
使用者已中止
 a| 
管理錯誤
 a| 
系統會顯示提示、要求您確認作業、並表示您不想執行該作業。



 a| 
36
 a| 
I/O串流錯誤
 a| 
管理錯誤
 a| 
系統輸入或系統輸出常式傳回SnapDrive 無法理解的UNIX錯誤。

執行SnapDrive、DC並將該資訊傳送給NetApp技術支援部門、以便他們協助您決定要執行哪些步驟來完成恢復。



 a| 
37
 a| 
檔案系統已滿
 a| 
管理錯誤
 a| 
嘗試寫入檔案失敗、因為檔案系統空間不足。當您在適當的檔案系統上釋出足夠空間時、UNIX版的可用空間仍可繼續。SnapDrive



 a| 
38
 a| 
檔案錯誤
 a| 
管理錯誤
 a| 
當UNIX的Runfi讀取或寫入系統組態檔或暫用檔案時、發生I/O錯誤SnapDrive 。



 a| 
39
 a| 
重複的磁碟群組
 a| 
命令錯誤
 a| 
嘗試啟動磁碟群組時、UNIX版的DB2有一個重複的次要節點編號。SnapDrive



 a| 
40
 a| 
檔案系統解調失敗。
 a| 
管理錯誤
 a| 
由於檔案系統上的系統活動、Snapcreate命令失敗。這通常發生在SnapDrive Snapshot複本所需的UNIX檔案系統當機、快照複本完成前就會逾時。



 a| 
43.
 a| 
名稱已在使用中
 a| 
命令錯誤
 a| 
UNIX版的支援功能嘗試建立磁碟群組、主機磁碟區、檔案系統或LUN、但名稱已在使用中。SnapDrive若要修正、請選取未使用的名稱、然後重新輸入SnapDrive 適用於UNIX的指令。



 a| 
44
 a| 
檔案系統管理程式錯誤
 a| 
致命的
 a| 
下列情況下、UNIX版的作業系統發生非預期的錯誤：SnapDrive

* 正在嘗試建立檔案系統
* 在檔案系統掛載表中輸入項目、以便在開機時自動掛載檔案系統。


此程式碼所顯示的錯誤訊息文字、說明檔案系統發生的錯誤。請記下訊息、並將其傳送給NetApp技術支援部門、以便他們協助您決定要執行哪些步驟來完成恢復。



 a| 
45
 a| 
掛載點錯誤
 a| 
管理錯誤
 a| 
檔案系統掛載點會出現在系統掛載表格檔案中。若要修正此問題、請選取掛載表中未使用或未列出的掛載點、然後重新輸入SnapDrive 「用作UNIX的版本」命令。



 a| 
46
 a| 
找不到LUN
 a| 
命令錯誤
 a| 
某個for UNIX命令嘗試存取儲存系統上不存在的LUN。SnapDrive

若要修正、請檢查LUN是否存在、以及是否正確輸入LUN名稱。



 a| 
47
 a| 
找不到啟動器群組
 a| 
管理錯誤
 a| 
無法如預期般存取儲存系統啟動器群組。因此SnapDrive 、適用於UNIX的功能無法完成目前的作業。

特定的錯誤訊息說明問題、以及解決問題所需執行的步驟。修正問題、然後重複執行命令。



 a| 
48
 a| 
物件離線
 a| 
管理錯誤
 a| 
UNIX版的支援嘗試存取物件（例如Volume）、但因為物件離線而失敗。SnapDrive



 a| 
49
 a| 
衝突的實體
 a| 
命令錯誤
 a| 
UNIX版的執行功能試圖建立一個igroup、但卻遇到一個名稱相同的igroup。SnapDrive



 a| 
50
 a| 
清除錯誤
 a| 
致命的
 a| 
UNIX版的物件應該移除、但仍然存在。SnapDrive



 a| 
51.
 a| 
磁碟群組ID衝突
 a| 
命令錯誤
 a| 
「不可靠的連線」命令會要求與現有磁碟群組發生衝突的磁碟群組ID。SnapDrive

這通常表示SnapDrive 在不支援的系統上、嘗試在來源主機上執行「支援鏈接」命令。若要修正此問題、請嘗試從其他主機執行作業。



 a| 
52.
 a| 
LUN未對應至任何主機
 a| 
管理錯誤
 a| 
LUN未對應至任何主機。換句話說、它不屬於儲存系統啟動器群組。若要存取、LUN必須對應至SnapDrive 目前的UNIX外部主機。



 a| 
53.
 a| 
LUN未對應至本機主機
 a| 
管理錯誤
 a| 
LUN未對應至目前的主機。換句話說、它不屬於包含目前主機啟動器的儲存系統啟動器群組。若要存取、LUN必須對應至SnapDrive 目前的UNIX外部主機。



 a| 
54
 a| 
LUN使用外部igroup對應
 a| 
管理錯誤
 a| 
LUN使用外部儲存系統啟動器群組進行對應。換句話說、它屬於儲存系統igroup、其中僅包含本機主機上找不到的啟動器。

因此SnapDrive 、UNIX版的功能無法刪除LUN。

若要使用SnapDrive for UNIX刪除LUN、LUN必須僅屬於本機igroup、也就是igroup只包含本機主機上找到的啟動器。



 a| 
55
 a| 
LUN使用混合式igroup對應
 a| 
管理錯誤
 a| 
LUN使用混合式儲存系統啟動器群組進行對應。也就是說、它屬於儲存系統igroup、其中包含本機主機上找到的啟動器和未在該主機上找到的啟動器。

因此SnapDrive 、UNIX版的功能無法中斷LUN連線。

若要使用SnapDrive for UNIX中斷LUN連線、LUN必須僅屬於本機igroup或異igroup、而非混合igroup。（本機igroup僅包含在本機主機上找到的啟動器；外部igroup包含在本機主機上找不到的啟動器。）



 a| 
56
 a| 
Snapshot複本還原失敗
 a| 
管理錯誤
 a| 
UNIX版的執行功能嘗試執行Snapshot還原作業、但在未還原Snapshot複本中的任何LUN的情況下失敗。SnapDrive

特定的錯誤訊息說明問題、以及解決問題所需執行的步驟。修正問題、然後重複執行命令。



 a| 
58
 a| 
需要重新開機主機
 a| 
管理錯誤
 a| 
主機作業系統需要重新開機才能更新內部資料。UNIX版的支援已準備好主機進行此更新、但無法完成目前的作業。SnapDrive

重新啟動主機、然後重新輸入SnapDrive 導致此訊息出現的UNIX適用的功能。重新開機之後、即可完成作業。



 a| 
59
 a| 
需要準備主機、LUN
 a| 
管理錯誤
 a| 
主機作業系統需要更新內部資料、才能完成目前的作業。若要建立新的LUN、必須進行此更新。

UNIX版無法執行更新、因為「sfapdrive.conf」變數「_enable、imitic-host-Prepared_」設定為「Off」、因此已停用主機資源配置的自動準備功能。SnapDrive停用自動主機準備功能時、您應該使用SnapDrive 「flexconfig prepare LUNs」命令來準備主機以配置LUN、或手動執行準備步驟。

若要避免此錯誤訊息、請在「snapdrive.conf」檔案中將「_enable、imitic-host-Prepared_」值設為「on」。



 a| 
62.
 a| 
不是空的
 a| 
命令錯誤
 a| 
發生錯誤、因為SnapDrive UNIX版的無法移除儲存系統磁碟區或目錄。當其他使用者或其他程序在SnapDrive 完全相同的時間和相同的目錄中建立檔案、而該目錄試圖刪除時、就可能發生這種情況。若要避免此錯誤、請確定一次只有一位使用者使用儲存系統磁碟區。



 a| 
63.
 a| 
逾時已過期
 a| 
命令錯誤
 a| 
發生錯誤、因為SnapDrive UNIX版的無法在50分鐘的逾時期間內還原LUN。

請記下訊息、並將其傳送給NetApp技術支援部門、以便他們協助您決定要執行哪些步驟來完成恢復。



 a| 
64
 a| 
服務未執行
 a| 
管理錯誤
 a| 
發生錯誤的原因是SnapDrive ：UNIX的flexfunix命令指定了NFS實體、而儲存系統並未執行NFS服務。



 a| 
126.
 a| 
不明錯誤
 a| 
管理錯誤
 a| 
發生不明錯誤、可能很嚴重。執行「snapdrive.DC」公用程式、並將其結果傳送給NetApp技術支援部門進行分析。



 a| 
127.
 a| 
內部錯誤
 a| 
致命的
 a| 
發生UNIX的內部錯誤。SnapDrive執行「snapdrive.DC」、並將結果傳送給NetApp技術支援部門進行分析。

|===