---
permalink: aix/task_starting_the_volume_or_lun_clone_split_start.html 
sidebar: sidebar 
keywords: snap, snapdrive, start, volume, clone, lun, split 
summary: 您可以啟動Volume Clone或LUN Clone切割作業。 
---
= 啟動Volume Clone或LUN Clone分割
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以啟動Volume Clone或LUN Clone切割作業。

.步驟
. 輸入下列命令以啟動磁碟區複製或LUN複製分割。
+
「SnapDrive *#」-實體複製切割開始[-LUN]_LON_LUN_name_[_LON_LUN_name_...] |[{-dg |-vg |-FS |-hostvol |-lvol}_file_spec_[_file_spec_...] [-force][-nodpromp][-dump |-dumpall]*

+
當儲存狀態顯示為「不可用」時、可使用下列選項。

+
** 您可以使用「-force」選項來強制啟動實體複本分割作業、並收到作業已啟動的確認訊息。
** 您可以使用「-noprompt」和「-force」選項來啟動複製分割啟動作業、而不會收到任何確認訊息。


+

NOTE: 當您在停止進行中的複本分割作業之後、立即啟動另一個複本分割作業時、該作業可能會失敗。如果啟動與停止複製分割作業之間的延遲不足以允許儲存系統同步停止作業、就可能發生此問題。



以下範例顯示如何分割Volume Clone：

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt4_0 /mnt/my_mnt3_0
Resource    Container  Required Available Storage
                       Space(MB)Space(MB) Status
--------------------------------------------------
/mnt/my_mnt4_0 f3050-220 3295   66033 AVAILABLE
             -111:aggr0
/mnt/my_mnt3_0 f3050-220  293   37707 AVAILABLE
             -112:aggr1

Job ID: B265Dbv8gh
Clone-Split for "/mnt/my_mnt4_0" is started
Clone-Split for "/mnt/my_mnt3_0" is started
----
以下範例顯示如何使用「_-force_'」選項分割實體複本：

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force
Resource    Container Required  Available Storage
                      Space(MB) Space(MB) Status
----------------------------------------------------
/mnt/my_mnt5 f3050-220 1198   20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294  2196  NOT AVAILABLE
             -112:aggr1
Not enough space available for Clone-Split.  Do you want to continue (y/n)?y
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----
以下範例說明如何使用「_-noprompt」選項直接啟動複本、表示沒有確認訊息：

[listing]
----
# snapdrive clone split start -fs /mnt/my_mnt5 /mnt/my_mnt6 -force -noprompt
Resource    Container  Required  Available Storage
                       Space(MB) Space(MB) Status
-----------------------------------------------------
/mnt/my_mnt5 f3050-220  1198     20033   AVAILABLE
             -111:aggr0
/mnt/my_mnt6 f3050-220  3294     2196  NOT AVAILABLE
             -112:aggr1
Clone-Split for "/mnt/my_mnt5" is started
Clone-Split for "/mnt/my_mnt6" is started
----