---
permalink: aix/task_generating_ca_signed_certificate.html 
sidebar: sidebar 
keywords: snap, snapdrive, generate, ca, certificate 
summary: for UNIX精靈服務需要您產生CA簽署的憑證、才能成功進行精靈通訊。SnapDrive您必須在SnapDrive .conf檔案中指定的路徑提供CA簽署的憑證。 
---
= 產生CA簽署的憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
for UNIX精靈服務需要您產生CA簽署的憑證、才能成功進行精靈通訊。SnapDrive您必須在「snapdrive.conf」檔案中指定的路徑提供CA簽署的憑證。

* 您必須以root使用者的身分登入。
* 您必須在「snapdrive.conf」檔案中設定下列參數、才能使用HTTPS進行通訊：
+
** use-https-to -SDU-daemon=on
** contact-https-port-sdU-daemon=4095
** SDU-daeme-Certificate路徑=（或）/opt/NetApp/SnapDrive / SnapDrive（磁碟機）.pem




.步驟
. 以pem格式產生新的未加密RSA私密金鑰：
+
「$openssl genrsa -out privkey.pem 10410*」

+
[listing]
----
Generating RSA private key, 1024 bit long modulus
 ....................++++++ ....................................++++++
e is 65537 (0x10001)
----
. 設定「/etc/ssl/openssl.cnf」以建立CA私密金鑰和憑證VI（如/etc/ssl/openssl.cnf）。
. 使用您的RSA私密金鑰建立未簽署的憑證：
+
「$openssl req - new -x509 -key privkey.pem -out cert.pem*」

+
[listing]
----
You are about to be asked to enter information that will be
incorporated into your certificate request.
What you are about to enter is what is called a Distinguished Name or
a DN.
There are quite a few fields but you can leave some blank For some
fields there will be a default value, If you enter '.', the field
will be left blank.
-----
Country Name (2 letter code) [XX]:NY
State or Province Name (full name) []:Nebraska Locality Name (eg,
city) [Default City]:Omaha Organization Name (eg, company) [Default
Company Ltd]:abc.com Organizational Unit Name (eg, section) []:
Common Name (eg, your name or your server's hostname) []:localhost
Email Address []:abc@example.org
----
. 使用您的私密金鑰和憑證來建立CSR：
+
「* cat cert.pem privkey.pem | openssl x509 -x509toreq -signkey privkey.pem -out certreq.csr*」

+
[listing]
----
Getting request Private Key Generating certificate request
----
. 使用您剛建立的CSR、以CA私密金鑰簽署憑證：
+
「$openssl ca -in certreq.csr -out newcert.pem*」

+
[listing]
----
Using configuration from /etc/pki/tls/openssl.cnf Check that the
request matches the signature Signature ok Certificate Details:
         Serial Number: 4096 (0x1000)
         Validity
            Not Before: May 17 06:02:51 2015 GMT
             Not After : May 16 06:02:51 2016 GMT
             Subject:
             countryName               = NY
             stateOrProvinceName       = Nebraska
             organizationName          = abc.com
             commonName                = localhost
             emailAddress              = abc@example.org
             X509v3 extensions:
             X509v3 Basic Constraints:
                 CA:FALSE
             X509v3 Key Usage:
                 Digital Signature, Non Repudiation, Key Encipherment
             Netscape Comment:
                 OpenSSL Generated Certificate
             X509v3 Subject Key Identifier:
                 FB:B0:F6:A0:9B:F2:C2:BC:50:BF:45:B2:9D:DB:AA:3B:C5:07:5B:7F
             X509v3 Authority Key Identifier:

 keyid:FB:B0:F6:A0:9B:F2:C2:BC:50:BF:45:B2:9D:DB:AA:3B:C5:07:5B:7F

 Certificate is to be certified until May 16 06:02:51 2016 GMT (365
 days) Sign the certificate? [y/n]:y


 1 out of 1 certificate requests certified, commit? [y/n]y Write out
 database with 1 new entries Data Base Updated
----
. 安裝SSL伺服器所使用的簽署憑證和私密金鑰。
+
[listing]
----
The newcert.pem is the certificate signed by your local CA that you can then use in an
ssl server:
( openssl x509 -in newcert.pem; cat privkey.pem ) > server.pem
ln -s server.pem `openssl x509 -hash -noout -in server.pem`.0 # dot-zero
( server.pem refers to location of https server certificate)
----

